---
- name: Install main tools
  become: true
  remote_user: ubuntu
  hosts: rpi4
  tasks: 

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      become: true
      become_user: root
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      become: true
      become_user: root
      apt: upgrade=dist force_apt_get=yes         
      ignore_errors: yes

    - name: Remove useless packages from the cache
      become: true
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      become: true
      apt:
        autoremove: yes

    - name: install devop tools
      become: true 
      become_user: root
      apt:
        state: present 
        name: 
         - net-tools
         - curl 
         - git 
         - rxvt-unicode
         - tmux  
         - xclip
         - tree
         - python3 
         - irssi

    - name: install IT tools
      become: true
      apt:
        state: present
        name:
        - bluez-tools
        - openssh-server
        - nmap
        - speedtest-cli
        - bridge-utils 

    - name: Install required system packages
      become: true
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest


    - name: install extra packages
      apt: name=figlet state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Add vagrant user to docker group
      user: 
        comment: used to run docker ps
        name: ubuntu
        shell: /bin/bash 
        group: docker 


